name: Release

on:
  push:
    tags:
      - v*

jobs:
  run:
    runs-on: ubuntu-latest
    environment: 'publish'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Build Package"
        run: uv build

      - name: "Publish package to PyPI"
        run: uv publish
